package turnorchestrator

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
	"strings"
	"sync"
	"time"
)

var safeID = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$`)

type realClock struct{}

func (realClock) Now() time.Time { return time.Now().UTC() }

type Orchestrator struct {
	deps   Dependencies
	policy Policy
}

func New(deps Dependencies, policy Policy) (*Orchestrator, error) {
	if deps.Compiler == nil || deps.Router == nil || deps.Supervisor == nil || deps.Runner == nil || deps.Verifier == nil || deps.Fallback == nil || deps.Eraser == nil {
		return nil, fmt.Errorf("missing required dependency")
	}
	if deps.Clock == nil {
		deps.Clock = realClock{}
	}
	if policy.DefaultTimeout <= 0 {
		policy.DefaultTimeout = 30 * time.Second
	}
	if policy.MaxTimeout <= 0 {
		policy.MaxTimeout = 2 * time.Minute
	}
	if policy.DefaultTimeout > policy.MaxTimeout {
		return nil, fmt.Errorf("default timeout exceeds maximum")
	}
	if policy.MaxRequestBytes <= 0 {
		policy.MaxRequestBytes = 64 * 1024
	}
	if policy.MaxPromptBytes <= 0 {
		policy.MaxPromptBytes = 2 * 1024 * 1024
	}
	if policy.MaxOutputBytes <= 0 {
		policy.MaxOutputBytes = 256 * 1024
	}
	if policy.MaxChunkBytes <= 0 {
		policy.MaxChunkBytes = 32 * 1024
	}
	if policy.MaxChunkBytes > policy.MaxOutputBytes {
		return nil, fmt.Errorf("chunk limit exceeds output limit")
	}
	if policy.CleanupTimeout <= 0 {
		policy.CleanupTimeout = 2 * time.Second
	}
	return &Orchestrator{deps: deps, policy: policy}, nil
}

// Run executes exactly one bounded turn. It never persists domain state and it
// never exposes unverified generated bytes as accepted output.
func (o *Orchestrator) Run(parent context.Context, req Request) Result {
	started := o.deps.Clock.Now()
	receipt := Receipt{
		Schema:       1,
		TurnID:       req.TurnID,
		StartedAt:    started,
		Outcome:      OutcomeFailed,
		FinalStage:   StageValidate,
		Reason:       ReasonNone,
		RequestBytes: len([]byte(req.Text)),
	}
	transient := &Transient{}

	timeout := req.Timeout
	if timeout <= 0 {
		timeout = o.policy.DefaultTimeout
	}
	if timeout > o.policy.MaxTimeout {
		timeout = o.policy.MaxTimeout
	}
	ctx, cancel := context.WithTimeout(parent, timeout)
	defer cancel()

	var lease Lease
	leaseReleased := false
	release := func(reason ReasonCode) ReasonCode {
		if lease == nil || leaseReleased {
			return reason
		}
		receipt.FinalStage = StageRelease
		cleanupCtx, cleanupCancel := context.WithTimeout(context.Background(), o.policy.CleanupTimeout)
		defer cleanupCancel()
		err := recoverErr(func() error { return lease.Release(cleanupCtx, reason) })
		leaseReleased = true
		receipt.LeaseReleased = err == nil
		if err != nil {
			return ReasonLeaseReleaseFailed
		}
		return reason
	}

	erase := func() bool {
		receipt.FinalStage = StageErase
		cleanupCtx, cleanupCancel := context.WithTimeout(context.Background(), o.policy.CleanupTimeout)
		defer cleanupCancel()
		err := recoverErr(func() error { return o.deps.Eraser.Erase(cleanupCtx, transient) })
		if err != nil {
			transient.Zero()
			receipt.ErasurePassed = false
			return false
		}
		receipt.ErasurePassed = true
		return true
	}

	finish := func(outcome Outcome, stage Stage, reason ReasonCode, text string) Result {
		receipt.Outcome = outcome
		receipt.FinalStage = stage
		receipt.Reason = reason
		receipt.CompletedAt = o.deps.Clock.Now()
		receipt.OutputBytes = len([]byte(text))
		receipt.ReceiptSHA256 = receiptDigest(receipt)
		return Result{Outcome: outcome, Text: text, Receipt: receipt}
	}

	failOrFallback := func(stage Stage, reason ReasonCode) Result {
		reason = release(reason)
		if reason == ReasonLeaseReleaseFailed {
			if !erase() {
				return finish(OutcomeFailed, StageErase, ReasonErasureFailed, "")
			}
			return finish(OutcomeFailed, StageRelease, reason, "")
		}
		if !erase() {
			return finish(OutcomeFailed, StageErase, ReasonErasureFailed, "")
		}
		if ctxReason(ctx) != ReasonNone {
			return finish(OutcomeCancelled, stage, ctxReason(ctx), "")
		}
		receipt.FinalStage = StageFallback
		fb, err := recoverValue(func() (FallbackOutput, error) {
			return o.deps.Fallback.Resolve(ctx, req, stage, reason)
		})
		if err != nil {
			mapped := ReasonFallbackFailed
			if errors.Is(err, errDependencyPanic) {
				mapped = ReasonDependencyPanic
			}
			return finish(OutcomeFailed, StageFallback, mapped, "")
		}
		if !validFallback(fb, o.policy.MaxOutputBytes) {
			return finish(OutcomeFailed, StageFallback, ReasonInvalidFallback, "")
		}
		receipt.FallbackID = fb.FallbackID
		return finish(OutcomeFallback, StageComplete, reason, fb.Text)
	}

	if reason := validateRequest(req, o.policy); reason != ReasonNone {
		if !erase() {
			return finish(OutcomeFailed, StageErase, ReasonErasureFailed, "")
		}
		return finish(OutcomeFailed, StageValidate, reason, "")
	}
	if reason := ctxReason(ctx); reason != ReasonNone {
		if !erase() {
			return finish(OutcomeFailed, StageErase, ReasonErasureFailed, "")
		}
		return finish(OutcomeCancelled, StageValidate, reason, "")
	}

	receipt.FinalStage = StageCompile
	compiled, err := recoverValue(func() (CompiledContext, error) { return o.deps.Compiler.Compile(ctx, req) })
	if err != nil {
		reason := ReasonCompileFailed
		if errors.Is(err, errDependencyPanic) {
			reason = ReasonDependencyPanic
		}
		return failOrFallback(StageCompile, reason)
	}
	if !validContext(compiled, req.TurnID, o.policy.MaxPromptBytes) {
		return failOrFallback(StageCompile, ReasonInvalidContext)
	}
	transient.Prompt = compiled.Prompt
	compiled.Prompt = nil
	receipt.ContextID = compiled.ContextID
	receipt.PromptBytes = len(transient.Prompt)

	receipt.FinalStage = StageRoute
	route, err := recoverValue(func() (Route, error) { return o.deps.Router.Route(ctx, compiled) })
	if err != nil {
		reason := ReasonRouteFailed
		if errors.Is(err, errDependencyPanic) {
			reason = ReasonDependencyPanic
		}
		return failOrFallback(StageRoute, reason)
	}
	if !validRoute(route, o.policy.MaxOutputBytes) {
		return failOrFallback(StageRoute, ReasonInvalidRoute)
	}
	receipt.RouteID = route.RouteID
	receipt.ModelSHA256 = route.ModelSHA256
	receipt.RuntimeSHA256 = route.RuntimeSHA256
	receipt.AdapterSHA256 = route.AdapterSHA256
	receipt.RouteSHA256 = digestJSON(route)

	receipt.FinalStage = StageAdmit
	lease, err = recoverValue(func() (Lease, error) { return o.deps.Supervisor.Admit(ctx, route) })
	if err != nil || lease == nil {
		reason := ReasonAdmissionDenied
		if errors.Is(err, errDependencyPanic) {
			reason = ReasonDependencyPanic
		}
		return failOrFallback(StageAdmit, reason)
	}
	leaseID, idErr := recoverValue(func() (string, error) { return lease.ID(), nil })
	if idErr != nil || !safeID.MatchString(leaseID) {
		reason := ReasonAdmissionDenied
		if errors.Is(idErr, errDependencyPanic) {
			reason = ReasonDependencyPanic
		}
		return failOrFallback(StageAdmit, reason)
	}
	receipt.LeaseID = leaseID

	runID := digestBytes([]byte(req.TurnID + "\x00" + compiled.ContextID + "\x00" + route.RouteID))[:32]
	receipt.RunID = runID
	transient.RuntimePrompt = append([]byte(nil), transient.Prompt...)
	input := GenerationInput{TurnID: req.TurnID, RunID: runID, Prompt: transient.RuntimePrompt, Route: route}

	generationCtx, stopGeneration := context.WithCancel(ctx)
	defer stopGeneration()
	collector := newCollector(req.TurnID, runID, min(route.MaxOutputBytes, o.policy.MaxOutputBytes), o.policy.MaxChunkBytes, generationCtx, stopGeneration)

	receipt.FinalStage = StageGenerate
	gen, err := recoverValue(func() (GenerationResult, error) {
		return o.deps.Runner.Generate(generationCtx, input, collector.Emit)
	})
	collector.Close()
	streamReason := collector.Reason()
	transient.Generated = collector.TakeBytes()
	receipt.ChunkCount = collector.ChunkCount()
	receipt.GeneratedBytes = len(transient.Generated)
	receipt.LateChunksSuppressed = collector.LateSuppressed()

	releaseReason := ReasonNone
	if err != nil {
		releaseReason = ReasonGenerationFailed
		if errors.Is(err, errDependencyPanic) {
			releaseReason = ReasonDependencyPanic
		}
	} else if streamReason != ReasonNone {
		releaseReason = streamReason
	} else if !validGeneration(gen, req.TurnID, runID) {
		releaseReason = ReasonInvalidGeneration
	} else if len(transient.Generated) == 0 {
		releaseReason = ReasonInvalidGeneration
	}
	if ctxReason(ctx) != ReasonNone {
		releaseReason = ctxReason(ctx)
	}
	releaseReason = release(releaseReason)
	if releaseReason != ReasonNone {
		if releaseReason == ReasonCancelled || releaseReason == ReasonTimedOut {
			if !erase() {
				return finish(OutcomeFailed, StageErase, ReasonErasureFailed, "")
			}
			return finish(OutcomeCancelled, StageGenerate, releaseReason, "")
		}
		return failOrFallback(StageGenerate, releaseReason)
	}
	receipt.TokenCount = gen.TokenCount
	receipt.FinishReason = boundedLabel(gen.FinishReason, 64)

	receipt.FinalStage = StageVerify
	transient.VerificationCopy = append([]byte(nil), transient.Generated...)
	verified, err := recoverValue(func() (VerifiedOutput, error) {
		return o.deps.Verifier.Verify(ctx, VerificationInput{
			TurnID:    req.TurnID,
			ContextID: compiled.ContextID,
			Route:     route,
			Generated: transient.VerificationCopy,
		})
	})
	if err != nil {
		reason := ReasonVerificationFailed
		if errors.Is(err, errDependencyPanic) {
			reason = ReasonDependencyPanic
		}
		return failOrFallback(StageVerify, reason)
	}
	if !verified.Accepted {
		return failOrFallback(StageVerify, ReasonVerificationRejected)
	}
	if !validVerified(verified, o.policy.MaxOutputBytes) {
		return failOrFallback(StageVerify, ReasonInvalidVerifiedOutput)
	}
	receipt.VerificationID = verified.VerificationID
	receipt.LateChunksSuppressed = collector.LateSuppressed()

	if !erase() {
		return finish(OutcomeFailed, StageErase, ReasonErasureFailed, "")
	}
	return finish(OutcomeAccepted, StageComplete, ReasonNone, verified.Text)
}

func validateRequest(req Request, policy Policy) ReasonCode {
	if !safeID.MatchString(req.TurnID) || strings.TrimSpace(req.Text) == "" || len([]byte(req.Text)) > policy.MaxRequestBytes || req.Timeout < 0 {
		return ReasonInvalidRequest
	}
	return ReasonNone
}

func validContext(c CompiledContext, turnID string, max int) bool {
	return c.TurnID == turnID && safeID.MatchString(c.ContextID) && len(c.Prompt) > 0 && len(c.Prompt) <= max
}

func validRoute(r Route, max int) bool {
	return safeID.MatchString(r.RouteID) && validDigest(r.ModelSHA256) && validDigest(r.RuntimeSHA256) && validDigest(r.AdapterSHA256) && r.MaxOutputBytes > 0 && r.MaxOutputBytes <= max
}

func validGeneration(g GenerationResult, turnID, runID string) bool {
	return g.TurnID == turnID && g.RunID == runID && g.Completed && g.TokenCount >= 0 && len(g.FinishReason) <= 64
}

func validVerified(v VerifiedOutput, max int) bool {
	return safeID.MatchString(v.VerificationID) && strings.TrimSpace(v.Text) != "" && len([]byte(v.Text)) <= max
}

func validFallback(f FallbackOutput, max int) bool {
	return f.Deterministic && safeID.MatchString(f.FallbackID) && strings.TrimSpace(f.Text) != "" && len([]byte(f.Text)) <= max
}

func ctxReason(ctx context.Context) ReasonCode {
	if ctx == nil || ctx.Err() == nil {
		return ReasonNone
	}
	if errors.Is(ctx.Err(), context.DeadlineExceeded) {
		return ReasonTimedOut
	}
	return ReasonCancelled
}

func digestBytes(b []byte) string {
	sum := sha256.Sum256(b)
	return hex.EncodeToString(sum[:])
}

func digestJSON(v any) string {
	b, _ := json.Marshal(v)
	return digestBytes(b)
}

func receiptDigest(r Receipt) string {
	r.ReceiptSHA256 = ""
	return digestJSON(r)
}

func validDigest(s string) bool {
	if len(s) != 64 {
		return false
	}
	_, err := hex.DecodeString(s)
	return err == nil && strings.ToLower(s) == s
}

func boundedLabel(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n]
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

func recoverValue[T any](fn func() (T, error)) (out T, err error) {
	defer func() {
		if recover() != nil {
			err = errDependencyPanic
		}
	}()
	return fn()
}

func recoverErr(fn func() error) (err error) {
	defer func() {
		if recover() != nil {
			err = errDependencyPanic
		}
	}()
	return fn()
}

type collector struct {
	mu       sync.Mutex
	turnID   string
	runID    string
	next     uint64
	maxTotal int
	maxChunk int
	ctx      context.Context
	cancel   context.CancelFunc
	open     bool
	reason   ReasonCode
	data     []byte
	chunks   int
	late     int
}

func newCollector(turnID, runID string, maxTotal, maxChunk int, ctx context.Context, cancel context.CancelFunc) *collector {
	return &collector{turnID: turnID, runID: runID, maxTotal: maxTotal, maxChunk: maxChunk, ctx: ctx, cancel: cancel, open: true, reason: ReasonNone}
}

func (c *collector) Emit(ch Chunk) error {
	c.mu.Lock()
	defer c.mu.Unlock()
	if !c.open {
		c.late++
		return errStreamClosed
	}
	if c.ctx.Err() != nil {
		c.open = false
		c.reason = ctxReason(c.ctx)
		return c.ctx.Err()
	}
	if ch.TurnID != c.turnID || ch.RunID != c.runID {
		c.fail(ReasonStreamIdentityMismatch)
		return errors.New("stream identity mismatch")
	}
	if ch.Sequence != c.next {
		c.fail(ReasonStreamSequenceViolation)
		return errors.New("stream sequence violation")
	}
	if len(ch.Data) == 0 || len(ch.Data) > c.maxChunk {
		c.fail(ReasonChunkTooLarge)
		return errors.New("invalid chunk size")
	}
	if len(c.data)+len(ch.Data) > c.maxTotal {
		c.fail(ReasonOutputTooLarge)
		return errors.New("output limit exceeded")
	}
	c.data = append(c.data, ch.Data...)
	c.next++
	c.chunks++
	return nil
}

func (c *collector) fail(reason ReasonCode) {
	c.reason = reason
	c.open = false
	c.cancel()
}

func (c *collector) Close() {
	c.mu.Lock()
	c.open = false
	c.mu.Unlock()
}

func (c *collector) Reason() ReasonCode { c.mu.Lock(); defer c.mu.Unlock(); return c.reason }
func (c *collector) TakeBytes() []byte {
	c.mu.Lock()
	defer c.mu.Unlock()
	out := c.data
	c.data = nil
	return out
}
func (c *collector) ChunkCount() int     { c.mu.Lock(); defer c.mu.Unlock(); return c.chunks }
func (c *collector) LateSuppressed() int { c.mu.Lock(); defer c.mu.Unlock(); return c.late }
